[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
